In [2]:
#Q.1 - Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.
import numpy as np
a=np.random.random([10,1])
print(a)
print("mean = ")
print(a.mean())


[[0.19645451]
 [0.18198529]
 [0.55793692]
 [0.27042222]
 [0.5613551 ]
 [0.99733393]
 [0.7244122 ]
 [0.23776727]
 [0.31043668]
 [0.99457319]]
mean = 
0.5032677299260128


In [3]:
#Q.2 - Create a numpy array with 20 elements of the shape(20,1) using np.random find the variance and standard deviation of the elements.
a=np.random.random([20,1])
print(a)
print("variance =")
print(a.var())
print("standard deviation = ")
print(a.std())


[[0.49376073]
 [0.39807202]
 [0.94490952]
 [0.94477496]
 [0.94127183]
 [0.72242051]
 [0.11447823]
 [0.02357918]
 [0.23281873]
 [0.21580624]
 [0.40000373]
 [0.33729725]
 [0.17837426]
 [0.58893724]
 [0.4647267 ]
 [0.81658476]
 [0.2347731 ]
 [0.42949956]
 [0.80666119]
 [0.5560698 ]]
variance =
0.07993679685338793
standard deviation = 
0.28273096196452896


In [4]:
#Q.3 - Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random.
 #Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25).
 #Using basic numpy math functions only find the sum of all the elements of the new matrix.

x=np.random.random([10,20])
y=np.random.random([20,25])
z=np.random.random([10,25])
print(x)
print(y)
print("multiplication of matrix is :")
print(np.matmul(x,y))
print("the sum of new matrix is :")
print(np.sum(z))


[[0.96342775 0.59252531 0.59653001 0.42095875 0.72859441 0.67227798
  0.91657145 0.77627817 0.86086956 0.97252601 0.05880058 0.33554248
  0.09336234 0.58938561 0.34168897 0.99143085 0.17768855 0.31573585
  0.6763194  0.73741941]
 [0.1694076  0.4928615  0.20288691 0.19664964 0.72441025 0.35732439
  0.47704913 0.75440229 0.71785762 0.85945411 0.62590348 0.89708817
  0.86870951 0.05661074 0.58374874 0.99290008 0.10817234 0.13868732
  0.68015113 0.96290965]
 [0.46164334 0.87483759 0.67408569 0.13882227 0.84509979 0.98525389
  0.93303645 0.20981736 0.2562389  0.81321829 0.04347969 0.59608177
  0.78039918 0.5146832  0.75073126 0.22073993 0.80322946 0.58245337
  0.91475583 0.60277696]
 [0.46867425 0.42170745 0.47029067 0.70009444 0.86989926 0.02878097
  0.3031957  0.05918927 0.86779658 0.54911382 0.22017499 0.39364432
  0.63702151 0.85367203 0.00965327 0.40953955 0.53762475 0.03352214
  0.77546039 0.33350805]
 [0.78649419 0.28699791 0.25129795 0.56858758 0.22520968 0.96262973
  0.07584919 0.7

In [5]:
#Q.4 - Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that
#each element is the following function applied on each element of A.
def show(i):
    return(1/(1+np.exp(-a)))
a=np.random.random([10,1])
b=[]
print(a)
for i in a:
    an=show(i)
    b.append(an)
    print(np.array(b))



[[0.87733935]
 [0.55024832]
 [0.62484057]
 [0.46642532]
 [0.92378848]
 [0.87934269]
 [0.19138187]
 [0.76081235]
 [0.7437775 ]
 [0.79181474]]
[[[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.54769996]
  [0.68153008]
  [0.67782134]
  [0.68822086]]]
[[[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.54769996]
  [0.68153008]
  [0.67782134]
  [0.68822086]]

 [[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.54769996]
  [0.68153008]
  [0.67782134]
  [0.68822086]]]
[[[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.54769996]
  [0.68153008]
  [0.67782134]
  [0.68822086]]

 [[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.54769996]
  [0.68153008]
  [0.67782134]
  [0.68822086]]

 [[0.70627057]
  [0.6341932 ]
  [0.65131866]
  [0.61453733]
  [0.7158134 ]
  [0.70668599]
  [0.5476